### ISSUE TITLE
Minor tweaks in README

### ISSUE THREAD

**Issue by duglin** [IBM/kubernetes-container-service-gitlab-sample#4]
`postgres` should be `gitlab-postgres` in postgres.yaml since the build cmd tags it as `gitlab-postgres`

`docker.io` should be `registry.ng.bluemix.net` in postgres.yaml and gitlab.yaml - why have them do the substitution on that part of the image names?

To fix it run:

```
sed -i "s/postgres:latest/gitlab-postgres:latest/" postgres.yaml
sed -i "s/docker.io/registry.ng.bluemix.net/" postgres.yaml 
sed -i "s/docker.io/registry.ng.bluemix.net/" gitlab.yaml
```

**Comment by Tomcli** [comment]
We updated our README and yaml files based on some of your suggestions. Thank you very much for your suggestions.
