### ISSUE TITLE
Postgres won't save when using a NFS PersistenVolume

### ISSUE THREAD

**Issue by corekartana** [IBM/Kubernetes-container-service-GitLab-sample#64]
I get this weird behavoir where the postgres pod makes the data folder on the PersistentVolume but nothing else - no files are written in the data folder.  I have also tried to change the mountPath from /var/lib/postgresql:rw to: /var/lib/postgresql/data:rw but then I get a permission denied. 

NFS Persistence volume
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: gitlab
spec:
  capacity:
  storage: 40Gi
accessModes:'
' - ReadWriteMany
nfs:'
'# OpenSuse NFS server' 
'path: "/srv/postgresql-gitlab/pgdata"
server: 192.168.1.16
readOnly: false`

I think the claim works since the data folder is been created by the postgres pod but here is the output of kubectl get pv --all-namespaces
`NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                      STORAGECLASS       REASON    AGE
postgresql-pv   40Gi       RWX            Retain           Bound     gitlab/postgres-pv-claim                            17m`

Anybody have an Idea to what is wrong? Any suggestions are appreciated.

**Comment by AnthonyAmanse** [comment]
@spunkmeier There has been a couple of update with the Kubernetes yaml configuration files in the repo. Can you try one more time?

Issue was addressed in this PR #63
